-- MySQL Script generated by MySQL Workbench
-- 2017年06月23日 星期五 08时39分06秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shixun
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shixun` ;

-- -----------------------------------------------------
-- Schema shixun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shixun` DEFAULT CHARACTER SET utf8 ;
USE `shixun` ;

-- -----------------------------------------------------
-- Table `shixun`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`book` ;

CREATE TABLE IF NOT EXISTS `shixun`.`book` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `ISBN` VARCHAR(32) NOT NULL,
  `author` VARCHAR(64) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `introduction` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`tags` ;

CREATE TABLE IF NOT EXISTS `shixun`.`tags` (
  `name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`book_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`book_tag` ;

CREATE TABLE IF NOT EXISTS `shixun`.`book_tag` (
  `book_id` INT(10) UNSIGNED NOT NULL,
  `tag_name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`book_id`, `tag_name`),
  INDEX `fk_book_tag_2_idx` (`tag_name` ASC),
  CONSTRAINT `fk_book_tag_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_tag_2`
    FOREIGN KEY (`tag_name`)
    REFERENCES `shixun`.`tags` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `introduction` VARCHAR(45) NOT NULL DEFAULT 'No Introduction yet.',
  `gender` ENUM('male', 'female') NOT NULL,
  `pic_src` VARCHAR(128) NOT NULL DEFAULT 'resource/pic/default.png',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`booklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`booklist` ;

CREATE TABLE IF NOT EXISTS `shixun`.`booklist` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `introduction` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_booklist_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_booklist_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`booklist_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`booklist_book` ;

CREATE TABLE IF NOT EXISTS `shixun`.`booklist_book` (
  `booklist_id` INT(10) UNSIGNED NOT NULL,
  `book_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`booklist_id`, `book_id`),
  INDEX `fk_booklist_book_2_idx` (`book_id` ASC),
  CONSTRAINT `fk_booklist_book_1`
    FOREIGN KEY (`booklist_id`)
    REFERENCES `shixun`.`booklist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booklist_book_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`booklist_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`booklist_tag` ;

CREATE TABLE IF NOT EXISTS `shixun`.`booklist_tag` (
  `booklist_id` INT(10) UNSIGNED NOT NULL,
  `tag_name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`booklist_id`, `tag_name`),
  INDEX `fk_booklist_tag_2_idx` (`tag_name` ASC),
  CONSTRAINT `fk_booklist_tag_1`
    FOREIGN KEY (`booklist_id`)
    REFERENCES `shixun`.`booklist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booklist_tag_2`
    FOREIGN KEY (`tag_name`)
    REFERENCES `shixun`.`tags` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`friend` ;

CREATE TABLE IF NOT EXISTS `shixun`.`friend` (
  `user_id1` INT(10) UNSIGNED NOT NULL,
  `user_id2` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id1`, `user_id2`),
  INDEX `fk_friend_2_idx` (`user_id2` ASC),
  CONSTRAINT `fk_friend_1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_friend_2`
    FOREIGN KEY (`user_id2`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`user_book_remark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_book_remark` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_book_remark` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `remark` VARCHAR(1024) NOT NULL,
  `remark_time` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_book_remark_2_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_book_remark_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_remark_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`user_booklist_remark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_booklist_remark` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_booklist_remark` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `booklist_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `remark` VARCHAR(1024) NOT NULL,
  `remark_time` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_booklist_remark_2_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_booklist_remark_1`
    FOREIGN KEY (`booklist_id`)
    REFERENCES `shixun`.`booklist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booklist_remark_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`user_interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_interest` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_interest` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `tag_name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`user_id`, `tag_name`),
  INDEX `fk_user_interest_2_idx` (`tag_name` ASC),
  CONSTRAINT `fk_user_interest_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_interest_2`
    FOREIGN KEY (`tag_name`)
    REFERENCES `shixun`.`tags` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shixun`.`user_book_opinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_book_opinion` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_book_opinion` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `vote` ENUM('up', 'down', 'netural') NOT NULL DEFAULT 'netural',
  `is_follow` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_user_book_2_idx` (`book_id` ASC),
  CONSTRAINT `fk_user_book_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_book_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shixun`.`user_booklist_opinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_booklist_opinion` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_booklist_opinion` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `vote` ENUM('up', 'down', 'netural') NOT NULL DEFAULT 'netural',
  `is_follow` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_user_book_2_idx` (`book_id` ASC),
  CONSTRAINT `fk_user_book_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_book_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`booklist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shixun`.`user_book_remark_opinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_book_remark_opinion` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_book_remark_opinion` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_remark_id` INT UNSIGNED NOT NULL,
  `vote` ENUM('up', 'down', 'netural') NOT NULL DEFAULT 'netural',
  PRIMARY KEY (`user_id`, `book_remark_id`),
  INDEX `fk_user_book_2_idx` (`book_remark_id` ASC),
  CONSTRAINT `fk_user_book_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_book_2`
    FOREIGN KEY (`book_remark_id`)
    REFERENCES `shixun`.`user_book_remark` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shixun`.`user_booklist_remark_opinion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shixun`.`user_booklist_remark_opinion` ;

CREATE TABLE IF NOT EXISTS `shixun`.`user_booklist_remark_opinion` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `vote` ENUM('up', 'down', 'netural') NOT NULL DEFAULT 'netural',
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_user_book_2_idx` (`book_id` ASC),
  CONSTRAINT `fk_user_book_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shixun`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_book_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `shixun`.`user_booklist_remark` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
